### ISSUE TITLE
Does RunReadOnly really work?

### ISSUE THREAD

**Issue by forestrf** [Jura-Z/TransformAccessArrayDemo#1]
I see you mention RunReadOnly as an option since Unity 2020.2. Have you tried it?
It doesn't work for me, it runs on the job threads and also prints to the console, as an error `Assertion failed on expression: 'jobParameters.dependency == JobFence()'`

If it doesn't work for you either, and if you have the time, given that you have source code access would you be so kind as to discover what in the black box Unity expects me to do for it to work?

Thank you a lot and sorry for opening an issue for something you aren't responsible of.

**Comment by Jura-Z** [comment]
Hey! Sorry for the delay! It works for me, but I'm currently using 2021.3.7f1, maybe there is some bug in previous versions?. See https://github.com/Jura-Z/TransformAccessArrayDemo/blob/main/TransformAccessArrayDemo/Assets/Scripts/DecalMovement/TransformAccessArrayWrapper/TransformAccessArrayWrapper.cs#L198

That's `ScheduleReadPositions` - I'm not really using it, just a demo on how to do that. I tried locally to call it, including the next variant:

```
        public JobHandle ScheduleReadPositions(JobHandle dependency)
        {
            dependency = JobHandle.CombineDependencies(dependency, m_ReadPositionsJobHandle, m_WritePositionsJobHandle);

            dependency.Complete();
            m_WritePositionsJobHandle = m_ReadPositionsJobHandle = default;
            new GetPositionsJob
                {
                    Positions = m_Positions,
                    Directions = m_Directions,
                }
                .RunReadOnly(m_Transforms);
            return default;
```

^ that's 'RunReadOnly' variation that runs everything on the main thread, so you still want to use `ScheduleReadOnly` instead.

Can you share your code so I can test it, maybe you setup dependency tree differently?

**Comment by forestrf** [comment]
I'm very sorry for the delay, thank you for your answer and taking the time.
I have the same problem with Unity 2021 and RunReadOnly, but I will just give up on that due to lack of time. The code is too convoluted and then the error feels like random, so I will assume it's due to some code I wrote idk when interfering somehow.
Again, sorry and thank you, really.
